### ISSUE TITLE
HTTP 521 Error

### ISSUE THREAD

**Issue by paulober** [asinf/unia.xyz#12]
Die Seite ist down. Und das auch noch während der Mario Kart Anmeldephase.
![image](https://github.com/asinf/unia.xyz/assets/44974737/3a6440af-ea3d-4145-901e-d375cb865d0d)

**Comment by paulober** [comment]
@Fanest

**Comment by Fanest** [comment]
Bei mir ist die Seite online und bei nem Freund von mir auch

**Comment by Fanest** [comment]
Kannst du Mal ein curl -vvv oder sowas Posten?

**Comment by Fanest** [comment]
@paulober kannst du schreiben ob es auch bei dir wieder geht?

**Comment by paulober** [comment]
Ja, klappt. Vielleicht könnte man noch einen Redirect oder CNAME von www auf die Domain machen.
